import { FileStack, RefreshCw } from 'lucide-react'
import { useState } from 'react'
import { Button } from '../../components/Button'
import type { ContentAsset, ContentChannel } from '../../types'
import { ChannelBadge, ComplianceBadge, QualityRing, TYPE_LABEL } from './ContentPrimitives'

export function ContentAssets({ assets, onOpenTask, onRefresh }: { assets: ContentAsset[]; onOpenTask: (id: string) => void; onRefresh: (asset: ContentAsset) => void }) {
  const [channel, setChannel] = useState<'all' | ContentChannel>('all')
  const [status, setStatus] = useState('all')
  const filtered = assets.filter((asset) => (channel === 'all' || asset.channels.includes(channel)) && (status === 'all' || asset.status === status))
  return <div className="content-page-stack"><div className="content-toolbar"><div><span className="content-eyebrow">CONTENT LIBRARY</span><h2>内容资产</h2><p>统一管理母稿、渠道版本、审核记录、有效期与阅读表现。</p></div><div className="content-asset-summary"><FileStack size={18} /><b>{assets.length}</b><span>份内容资产</span></div></div><div className="content-filterbar"><select value={channel} onChange={(e) => setChannel(e.target.value as 'all' | ContentChannel)}><option value="all">全部渠道</option><option value="website">企业网站</option><option value="linkedin">LinkedIn</option><option value="facebook">Facebook</option><option value="x">X / Twitter</option></select><select value={status} onChange={(e) => setStatus(e.target.value)}><option value="all">全部状态</option><option value="draft">草稿</option><option value="reviewing">审核中</option><option value="published">已发布</option><option value="needs_update">待更新</option><option value="retired">已下架</option></select><span>{filtered.length} 项结果</span></div><section className="content-table-card"><div className="table-wrap"><table className="content-data-table"><thead><tr><th>内容资产</th><th>质量</th><th>合规</th><th>渠道版本</th><th>阅读表现</th><th>有效期</th><th>操作</th></tr></thead><tbody>{filtered.map((asset) => <tr key={asset.id}><td><b>{asset.title}</b><span>{TYPE_LABEL[asset.type]} · {asset.language} · 更新于 {asset.updatedAt}</span></td><td><QualityRing score={asset.qualityScore} size="sm" /></td><td><ComplianceBadge level={asset.compliance} /></td><td><div className="content-channel-cell">{asset.channels.map((item) => <ChannelBadge key={item} channel={item} />)}</div></td><td><b>{asset.uv || '—'} UV</b><span>{asset.effectiveReadRate ? `有效阅读 ${asset.effectiveReadRate}%` : '尚未发布'}</span></td><td><span>{asset.expiresAt}</span>{asset.status === 'needs_update' && <em className="content-expire-warning">需要更新</em>}</td><td><div className="content-row-actions"><Button size="sm" variant="text" onClick={() => onOpenTask(asset.taskId)}>查看</Button><Button size="sm" variant="secondary" onClick={() => onRefresh(asset)}><RefreshCw size={13} />更新</Button></div></td></tr>)}</tbody></table></div></section></div>
}
