import { AlertTriangle, Check, Clock3, ExternalLink, RefreshCw, Send } from 'lucide-react'
import { Button } from '../../components/Button'
import type { PublicationRecord } from '../../types'
import { ChannelBadge } from './ContentPrimitives'

const LABELS = { pending_approval: '待审批', scheduled: '已排期', published: '已发布', partial: '部分成功', failed: '发布失败', retired: '已下架' } as const

export function ContentPublishing({ records, onApprove, onRetry }: { records: PublicationRecord[]; onApprove: (id: string) => void; onRetry: (id: string) => void }) {
  return <div className="content-page-stack"><div className="content-toolbar"><div><span className="content-eyebrow">PUBLISHING CENTER</span><h2>发布管理</h2><p>统一审批、排期和追踪网站及社媒发布结果。</p></div><Button variant="secondary"><Send size={15} />发布设置</Button></div><div className="content-publish-board">{records.map((record) => <article key={record.id} className={`content-publish-card is-${record.status}`}><header><div><span className="content-publish-state">{LABELS[record.status]}</span><h3>{record.title}</h3><p>{record.scheduledAt ? `计划时间 ${record.scheduledAt}` : '等待审批后配置发布时间'}</p></div>{record.status === 'pending_approval' && <Button size="sm" onClick={() => onApprove(record.id)}>审批通过</Button>}{(record.status === 'partial' || record.status === 'failed') && <Button size="sm" onClick={() => onRetry(record.id)}><RefreshCw size={13} />重试失败渠道</Button>}</header><div className="content-publish-channels">{record.channels.map((version) => <div key={version.channel} className={`is-${version.status}`}><ChannelBadge channel={version.channel} /><span className="content-publish-channel-status">{version.status === 'published' && <Check size={13} />}{version.status === 'scheduled' && <Clock3 size={13} />}{version.status === 'failed' && <AlertTriangle size={13} />}{version.status === 'ready' ? '待发布' : version.status === 'published' ? '已发布' : version.status === 'scheduled' ? version.scheduledAt : version.status === 'failed' ? '失败' : '草稿'}</span>{version.url && <a href={version.url} target="_blank" rel="noreferrer"><ExternalLink size={13} />查看</a>}{version.error && <small>{version.error}</small>}</div>)}</div>{record.approvedBy && <footer>审批人：{record.approvedBy}</footer>}</article>)}</div></div>
}
