import { ArrowLeft, Check, ChevronRight, CircleAlert, FileCheck2, Library, Send, Sparkles } from 'lucide-react'
import { useState } from 'react'
import { Button } from '../../components/Button'
import type { ContentChannel, ContentTask } from '../../types'
import { ChannelBadge, CHANNEL_META, QualityRing, StatusBadge } from './ContentPrimitives'

const STEPS = ['任务简报', '资料与素材', '母稿生产', '质量与合规', '渠道版本', '审批与发布']

export function ContentWorkbench({ task, onBack, onResolveCompliance, onAdvance }: { task: ContentTask; onBack: () => void; onResolveCompliance: (taskId: string) => void; onAdvance: (taskId: string) => void }) {
  const [step, setStep] = useState(task.status === 'compliance_review' ? 3 : task.status === 'pending_approval' ? 5 : task.status === 'needs_material' ? 1 : 2)
  const [channel, setChannel] = useState<ContentChannel>(task.channelVersions[0]?.channel ?? task.channels[0] ?? 'website')
  const blockers = task.compliance.filter((item) => !item.resolved && (item.level === 'blocking' || item.level === 'high'))
  const version = task.channelVersions.find((item) => item.channel === channel)

  return <div className="content-workbench">
    <div className="content-workbench__top"><button onClick={onBack}><ArrowLeft size={16} />返回内容计划</button><div><span className={`content-priority is-${task.priority.toLowerCase()}`}>{task.priority}</span><h2>{task.title}</h2><StatusBadge status={task.status} /></div></div>
    <div className="content-stepper">{STEPS.map((label, index) => <button key={label} className={`${step === index ? 'is-active' : ''} ${index < step ? 'is-done' : ''}`} onClick={() => setStep(index)}><span>{index < step ? <Check size={13} /> : index + 1}</span><b>{label}</b>{index < STEPS.length - 1 && <ChevronRight size={14} />}</button>)}</div>

    <section className="content-workbench__body">
      {step === 0 && <div className="content-workbench-grid"><div className="content-panel"><span className="content-eyebrow">CONTENT BRIEF</span><h3>任务说明</h3><dl className="content-detail-list"><div><dt>目标受众</dt><dd>{task.audience}</dd></div><div><dt>访客问题</dt><dd>{task.userQuestion}</dd></div><div><dt>内容主题</dt><dd>{task.theme}</dd></div><div><dt>任务依据</dt><dd>{task.reason}</dd></div><div><dt>计划时间</dt><dd>{task.dueDate}</dd></div></dl></div><div className="content-panel"><span className="content-eyebrow">TARGET CHANNELS</span><h3>目标渠道</h3><div className="content-channel-stack">{task.channels.map((item) => <ChannelBadge key={item} channel={item} />)}</div><div className="content-note"><Sparkles size={16} /><p>先形成统一事实和核心表达，再从母稿生成各渠道版本。</p></div></div></div>}

      {step === 1 && <div className="content-workbench-grid"><div className="content-panel"><div className="content-panel__head"><div><span className="content-eyebrow">KNOWLEDGE REFERENCES</span><h3>知识库调用结果</h3></div><Library size={20} /></div><div className="content-reference-list">{task.knowledge.length ? task.knowledge.map((ref) => <div key={ref.id}><span className={ref.verified ? 'is-verified' : ''}>{ref.verified ? <Check size={12} /> : '!'}</span><p><b>{ref.title}</b><small>{ref.category} · {ref.source}</small></p></div>) : <p className="muted">任务开始后将调用企业与行业知识库。</p>}</div></div><div className="content-panel"><span className="content-eyebrow">MISSING MATERIALS</span><h3>缺失资料</h3>{task.missingMaterials.length ? <div className="content-missing-list">{task.missingMaterials.map((item) => <div key={item}><CircleAlert size={15} />{item}<button>发起补充</button></div>)}</div> : <div className="content-empty-success"><FileCheck2 size={28} /><b>资料已准备完整</b><span>关键事实均有可追溯来源</span></div>}</div></div>}

      {step === 2 && <div className="content-draft-layout"><aside className="content-outline"><span className="content-eyebrow">OUTLINE</span><h3>内容大纲</h3>{task.outline.map((item, index) => <button key={item}><span>{String(index + 1).padStart(2, '0')}</span>{item}</button>)}</aside><div className="content-editor"><div className="content-editor__head"><div><span className="content-eyebrow">MASTER CONTENT</span><h3>内容母稿</h3></div><div><Button size="sm" variant="secondary">调整语气</Button><Button size="sm"><Sparkles size={14} />AI 重写</Button></div></div><div className="content-editor__canvas"><h1>{task.title}</h1>{task.masterDraft ? task.masterDraft.split('\n\n').map((p) => <p key={p}>{p}</p>) : <div className="content-generating-state"><Sparkles size={30} /><b>等待生成内容母稿</b><span>将基于已确认大纲和知识资料生成</span><Button onClick={() => onAdvance(task.id)}>开始生成</Button></div>}</div></div></div>}

      {step === 3 && <div className="content-review-grid"><section className="content-panel content-score-panel"><div><span className="content-eyebrow">QUALITY SCORE</span><h3>内容质量</h3></div><QualityRing score={task.quality.overall} /><div className="content-score-bars">{[['需求匹配', task.quality.relevance, 20], ['专业准确', task.quality.accuracy, 20], ['内容完整', task.quality.completeness, 20], ['清晰易读', task.quality.readability, 15], ['企业真实', task.quality.authenticity, 15], ['渠道适配', task.quality.channelFit, 10]].map(([label, value, max]) => <div key={String(label)}><span>{label}</span><i><b style={{ width: `${(Number(value) / Number(max)) * 100}%` }} /></i><em>{value}/{max}</em></div>)}</div></section><section className="content-panel"><div className="content-panel__head"><div><span className="content-eyebrow">COMPLIANCE REVIEW</span><h3>合规检查</h3></div><span className={`content-risk-summary ${blockers.length ? 'has-risk' : ''}`}>{blockers.length ? `${blockers.length} 项需处理` : '已通过'}</span></div><div className="content-compliance-list">{task.compliance.length ? task.compliance.map((issue) => <article key={issue.id} className={`is-${issue.level} ${issue.resolved ? 'is-resolved' : ''}`}><span>{issue.resolved ? <Check size={14} /> : '!'}</span><div><b>{issue.title}</b><p>{issue.detail}</p><small>{issue.category} · {issue.level}</small></div></article>) : <div className="content-empty-success"><FileCheck2 size={28} /><b>未发现合规风险</b><span>可进入渠道适配与发布流程</span></div>}</div>{blockers.length > 0 && <Button block onClick={() => onResolveCompliance(task.id)}>接受建议并处理风险</Button>}</section></div>}

      {step === 4 && <div className="content-channel-editor"><div className="content-channel-editor__tabs">{task.channels.map((item) => <button key={item} className={channel === item ? 'is-active' : ''} onClick={() => setChannel(item)}><ChannelBadge channel={item} /></button>)}</div><div className="content-channel-preview"><div className="content-channel-preview__meta"><span style={{ background: CHANNEL_META[channel].color }}>{CHANNEL_META[channel].short}</span><div><b>{CHANNEL_META[channel].label}</b><small>{version?.account ?? '待选择账号'}</small></div><em>{version ? '版本已生成' : '待生成'}</em></div>{version ? <div className="content-channel-preview__body"><h3>{version.title}</h3><p>{version.body}</p><div className="content-preview-placeholder">视觉素材预览</div></div> : <div className="content-generating-state"><Sparkles size={30} /><b>尚未生成该渠道版本</b><Button onClick={() => onAdvance(task.id)}>生成渠道版本</Button></div>}</div></div>}

      {step === 5 && <div className="content-approval-layout"><section className="content-panel"><span className="content-eyebrow">APPROVAL</span><h3>审批状态</h3><div className="content-approval-card"><span className={blockers.length ? 'is-blocked' : 'is-ready'}>{blockers.length ? '!' : <Check size={18} />}</span><div><b>{blockers.length ? '尚未满足发布条件' : '内容已满足审批条件'}</b><p>{blockers.length ? '请先处理高风险合规问题。' : '母稿、渠道版本和合规检查均已完成。'}</p></div></div><dl className="content-detail-list"><div><dt>审批人</dt><dd>张敏 · 市场运营</dd></div><div><dt>发布模式</dt><dd>人工审核</dd></div><div><dt>发布渠道</dt><dd>{task.channels.length} 个</dd></div></dl></section><section className="content-panel"><span className="content-eyebrow">SCHEDULE</span><h3>发布配置</h3><label className="content-form-field"><span>发布时间</span><input type="datetime-local" defaultValue="2026-08-03T10:00" /></label><label className="content-form-field"><span>失败策略</span><select defaultValue="continue"><option value="continue">其他渠道继续发布</option><option value="stop">任一失败则停止整组</option></select></label><Button block disabled={blockers.length > 0} onClick={() => onAdvance(task.id)}><Send size={15} />审批通过并加入排期</Button></section></div>}
    </section>
  </div>
}
